VECTOR_SOURCE_TRACKING_FILE: "{{ VECTOR_SOURCE_TRACKING_FILE }}"
VECTOR_SINK_CLICKHOUSE_ENDPOINT: "{{ VECTOR_SINK_CLICKHOUSE_ENDPOINT }}"
VECTOR_AWS_ACCESS_KEY_ID: "{{ VECTOR_SINK_CLICKHOUSE_ENDPOINT }}"
VECTOR_AWS_SECRET_ACCESS_KEY: "{{ VECTOR_AWS_SECRET_ACCESS_KEY }}"
VECTOR_AWS_STORAGE_BUCKET_NAME: "{{ VECTOR_AWS_STORAGE_BUCKET_NAME }}"
VECTOR_S3_REGION: "{{ VECTOR_S3_REGION }}"
ENABLE_VECTOR_SINK_S3: "{{ ENABLE_VECTOR_SINK_S3 }}"
