# Bootstrap packages must be installed with raw commands, because ubuntu
# xenial+ cloud images don't have python2.7 installed, and ansible doesn't yet
# support python3.

- name: Wait until cloud-init has finished running
  raw: test -e /usr/bin/cloud-init && cloud-init status --wait
  ignore_errors: yes

- name: Remove expired nginx key
  raw: "apt-key del 7BD9BF62"
  ignore_errors: yes
  become: yes

- name: Download and add Nginx signing key (force overwrite)
  shell: |
    curl -fsSL https://nginx.org/keys/nginx_signing.key | gpg --dearmor | tee /usr/share/keyrings/nginx-archive-keyring.gpg > /dev/null
  args:
    warn: false
  become: yes

- name: Remove existing Nginx repository file if it exists
  file:
    path: /etc/apt/sources.list.d/nginx.list
    state: absent
  become: yes

- name: Ensure the Nginx repository is configured correctly
  shell: |
    echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/ubuntu xenial nginx" | tee /etc/apt/sources.list.d/nginx.list
  become: yes

- name: Debug installed GPG keys
  shell: apt-key list
  register: gpg_keys
  changed_when: false

- debug:
    msg: "{{ gpg_keys.stdout_lines }}"

- name: Debug Nginx repository configuration
  shell: cat /etc/apt/sources.list.d/nginx.list
  register: nginx_repo
  changed_when: false

- debug:
    msg: "{{ nginx_repo.stdout_lines }}"

- name: Update apt-get
  raw: apt-get update -qq
  register: python_update_result
  until: python_update_result.rc == 0
  retries: 10
  delay: 10

- name: Install packages
  raw: "apt-get install -qq {{ item }}"
  with_items: "{{ python_packages }}"
  retries: 10
  delay: 10
