# Bootstrap packages must be installed with raw commands, because ubuntu
# xenial+ cloud images don't have python2.7 installed, and ansible doesn't yet
# support python3.

- name: Wait until cloud-init has finished running
  raw: test -e /usr/bin/cloud-init && cloud-init status --wait
  ignore_errors: yes

#- name: Remove expired nginx key
#  raw: "apt-key del 7BD9BF62"
#  ignore_errors: yes
#  become: yes

- name: Remove conflicting Nginx sources (if exists)
  raw: rm -f /etc/apt/sources.list.d/nginx.list
  ignore_errors: yes

- name: Ensure correct Nginx signing key is added
  raw: |
    curl -fsSL https://nginx.org/keys/nginx_signing.key | tee /usr/share/keyrings/nginx-archive-keyring.gpg > /dev/null
  ignore_errors: yes

- name: Add correct Nginx repository
  raw: |
    echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/ubuntu/ $(lsb_release -cs) nginx" | tee /etc/apt/sources.list.d/nginx.list
  ignore_errors: yes

- name: Debug APT sources to verify Nginx repo
  raw: cat /etc/apt/sources.list.d/nginx.list
  register: nginx_repo_check
  ignore_errors: yes

- name: Display Nginx repo debug output
  debug:
    msg: "{{ nginx_repo_check.stdout_lines }}"

- name: Update apt-get
  raw: apt-get update -qq
  register: python_update_result
  until: python_update_result.rc == 0
  retries: 10
  delay: 10

- name: Install packages
  raw: "apt-get install -qq {{ item }}"
  with_items: "{{ python_packages }}"
  retries: 10
  delay: 10
